### ISSUE TITLE
[Feature Request] Proxy Support?

### ISSUE THREAD

**Issue by NullPointDev** [mcpcpc/kirc#98] opened 2021-02-04 00:34 UTC
**Is your feature request related to a problem? Please describe.**
I like having this nice lightweight IRC client, but I often find myself at a road block connecting from anywhere other than home. Proxies tend to get in the way of network traffic due to authentication requirements, and having an app that doesn't accommodate this tends to be annoying.

**Describe the solution you'd like**
I would really like to have a connection option or file for configuring a proxy, or at the least an automatic proxy detection/authentication system. e.g. "Proxy Authentication Required: (username/password prompt)"

**Describe alternatives you've considered**
A lot of other IRC clients work with this sort of feature, but I'm looking for something nice and simple to use from the command line, and none of those seem to fit that description.

**Additional context**
`N/A`

**Comment by mcpcpc** [comment] 2021-02-04 02:42
Hi Leo,

Thanks for the feedback. Regarding proxy support, while the implementation would be fairly straight forward, I am slightly hesitant to add this functionality at this time. Since the early public releases of kirc, I have accepted many feature requests and rejected some for sole reason of utility or scope.  In this case, the “utility” (e.g. proxy server support) can readily be accomplished via third-part applications, such as `socat`, without being implemented directly into kirc.  This would be my preferred route as most third-party applications can manage lightweight applications like kirc with little overhead and introduce less risk (i.e security or bugs) to the end-user.

I can sympathize for your proxy woes though, especially when in a corporate setting.  If I have some time this weekend, I will try to enhance the support documentation and see if I can put together some examples using different different third-party applications. 

Per usual, I am open to counter arguments to anything I have stated above. =)

Useful Reference: https://www.radarhack.com/tutorial/DEFEATING_THE_NETWORK_SECURITY_INFRASTRUCTURE.pdf

-mcpcpc

**Comment by mcpcpc** [comment] 2021-02-05 16:06
Hi Leo

Just a small update.  I have been attempting to use `socat` to connect to freenode using a proxy server with little success.  From what i was able to infer from the man page, you should be able to do something like the following:

``
socat tcp-listen:6697,fork,reuseaddr,bind=127.0.0.1 proxy:<proxy_server>:<destination_hostname>:<destination_port>,proxyport=<proxy_port>
kirc -s 127.0.0.1 -n mcpcpc -p 6697
```

**Comment by mcpcpc** [comment] 2021-02-05 16:28
actually, I can confirm that this DOES work, just not with kirc at the moment. For example, using `netcat`:
```
$ socat tcp-listen:6667,fork,reuseaddr,bind=127.0.0.1 proxy:<proxy_server>:irc.freenode.org,proxyport=80
$ nc 127.0.0.1 6667
:hitchcock.freenode.net NOTICE * :*** Looking up your hostname...
:hitchcock.freenode.net NOTICE * :*** Checking Ident
:hitchcock.freenode.net NOTICE * :*** Couldn't look up your hostname
:hitchcock.freenode.net NOTICE * :*** No Ident response
```

kirc, however, closes the connection immediately.  tbd on why...

**Comment by mcpcpc** [comment] 2021-02-12 17:30
I have update the support documentation (see https://github.com/mcpcpc/kirc/commit/1f4dd5c0388c8a9ec90cc16b5a4c24ab9a7cdc62), which hopefully should be substantial enough to address the proxy support concern. 

@NullPointDev: With this updated documentation, I will go ahead and close this issue for now.  Please feel free to contact me or re-open this issue if you have any additional concerns.

**Closed** 2021-02-12 17:31 UTC
Labels: documentation, enhancement
