### ISSUE TITLE
xdcc support

### ISSUE THREAD

**Issue by stefan11111** [mcpcpc/kirc#131] opened 2023-01-02 12:37 UTC
I can't find anything mentioning how to set the xdcc downloads directory and how to accept xdcc requests and how to configure kirc to always accept them. I if is already a feature, can somebody tell me how to use it or point me in the right direction? and if it isn't, can it be added?

**Comment by emekoi** [comment] 2023-01-05 02:30
its not currently a feature but its easy enough to add a rough implementation. the following patch unconditionally downloads files in the current directory without any checking of the filename. furthermore, it uses fork to keep things simple. it also doesn't print out any progress or support dcc request with ipv6 address, however it does support mIRC style dcc transfers larger than 4GB albeit the support is somewhat buggy. if this is something actually wanted i would be glad to open a pull request with a proper implementation.
```patch
diff --git a/kirc.c b/kirc.c
index 2501005..0807635 100644
--- a/kirc.c
+++ b/kirc.c
@@ -16,8 +16,11 @@
 #include <errno.h>
 #include <termios.h>
 #include <sys/ioctl.h>
+#include <netinet/in.h>
+#include <stdint.h>
+#include <arpa/inet.h>
 
-#define CTCP_CMDS "ACTION VERSION TIME CLIENTINFO PING"
+#define CTCP_CMDS "ACTION VERSION TIME CLIENTINFO PING DCC"
 #define VERSION "0.3.1"
 #define MSG_MAX 512
 #define CHA_MAX 200
@@ -729,22 +732,87 @@ static void paramPrintJoin(struct Param *p) {
 	}
 }
 
-static void handleCTCP(const char *nickname, char *message) {
+static void handleDCC(struct Param *p) {
+	/* eat DCC prefix */
+	const char *message = p->message + 5;
+
+	if (!strncmp(message, "SEND", 4)) {
+		char filename[256];
+		uint64_t size = 0;
+		uint32_t addr = 0;
+		uint16_t port = 0;
+
+		if (sscanf(message, "SEND \"%255[^\"]\" %u %hu %zu", filename, &addr, &port, &size) != 4) {
+			if (sscanf(message, "SEND %255s %u %hu %zu", filename, &addr, &port, &size) != 4) {
+				printf("error reading dcc message: '%s'\r\n", message);
+				return;
+			}
+		}
+
+		if (fork()) return;
+
+		struct sockaddr_in sockaddr = (struct sockaddr_in){
+			.sin_family = AF_INET,
+			.sin_addr = (struct in_addr){htonl(addr)},
+			.sin_port = htons(port),
+		};
+
+		int sock_fd = socket(AF_INET,SOCK_STREAM, 0);
+		if (sock_fd < 0) {
+			perror("socket");
+			_exit(1);
+		}
+		if (connect(sock_fd, (const struct sockaddr*)&sockaddr, sizeof(sockaddr)) < 0) {
+			perror("connect");
+			close(sock_fd);
+			_exit(1);
+		}
+
+		int file_fd = open(filename, O_WRONLY | O_CREAT, S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH);
+		if (file_fd < 0) {			
+			perror("open");
+			close(sock_fd);
+			_exit(1);
+		}
+
+		char *buf = calloc(BUFSIZ, sizeof(char));
+		uint64_t total_bytes = 0;
+		uint32_t ack64 = size > UINT32_MAX;
+		uint32_t ack_shift = (1 - ack64) * 32;
+
+		for (ssize_t n = 0; (n = read(sock_fd, buf, BUFSIZ)); ) {
+			total_bytes += n;
+			uint64_t ack = __builtin_bswap64(total_bytes << ack_shift);
+			write(sock_fd, &ack, ack64 ? sizeof(uint64_t) : sizeof(uint32_t));
+			write(file_fd, buf, n);
+		}
+
+		close(file_fd);
+		shutdown(sock_fd, SHUT_RDWR);
+		close(sock_fd);		
+		_exit(0);
+	}
+}
+
+static void handleCTCP(struct Param *p) {
+	const char *message = p->message;
 	if (message[0] != '\001' && strncmp(message, "ACTION", 6)) {
 		return;
 	}
 	message++;
 	if (!strncmp(message, "VERSION", 7)) {
-		raw("NOTICE %s :\001VERSION kirc " VERSION "\001\r\n", nickname);
+		raw("NOTICE %s :\001VERSION kirc " VERSION "\001\r\n", p->nickname);
 	} else if (!strncmp(message, "TIME", 7)) {
 		char buf[26];
 		if (!ctime_now(buf)) {
-			raw("NOTICE %s :\001TIME %s\001\r\n", nickname, buf);
+			raw("NOTICE %s :\001TIME %s\001\r\n", p->nickname, buf);
 		}
 	} else if (!strncmp(message, "CLIENTINFO", 10)) {
-		raw("NOTICE %s :\001CLIENTINFO " CTCP_CMDS "\001\r\n", nickname);
+		raw("NOTICE %s :\001CLIENTINFO " CTCP_CMDS "\001\r\n", p->nickname);
 	} else if (!strncmp(message, "PING", 4)) {
-		raw("NOTICE %s :\001%s\r\n", nickname, message);
+		raw("NOTICE %s :\001%s\r\n", p->nickname, message);
+	} else if (!strncmp(message, "DCC", 3)) {
+		handleDCC(p);
 	}
 }
 
@@ -754,7 +822,7 @@ static void paramPrintPriv(struct Param *p) {
 		s = p->nicklen - strnlen(p->nickname, MSG_MAX);
 	}
 	if (p->channel != NULL && (strcmp(p->channel, nick) == 0)) {
-		handleCTCP(p->nickname, p->message);
+		handleCTCP(p);
 		printf("%*s\x1b[33;1m%-.*s\x1b[36m ", s, "", p->nicklen, p->nickname);
 	} else if (p->channel != NULL && strcmp(p->channel + 1, cdef)) {
 		printf("%*s\x1b[33;1m%-.*s\x1b[0m", s, "", p->nicklen, p->nickname);
```

**Comment by mcpcpc** [comment] 2023-01-05 04:15
@emekoi I would welcome the pull request!

**Comment by stefan11111** [comment] 2023-01-05 14:24
I am going to request one more thing.
the /msg command is not supported.
Can it be aliased to the @ command that is already implemented. Also, if I replace /msg with /privmsg the result is different that using @

**Comment by emekoi** [comment] 2023-01-05 16:50
`MSG` is not an irc command. from what i can tell it's just a shorthand for `PRIVMSG`. furthermore, looking at the commands sent using verbose mode, `PRIVMSG` and the `@` shorthand result in the exact same message.

**Comment by stefan11111** [comment] 2023-01-05 18:36
I have looked into this a bit with -V.
here is the output of /privmsg vs @ tested using irc.rizon.net NickServ:

/privmsg NickServ IDENTIFY password
>> :NickServ!service@rizon.net NOTICE hentai_god :Syntax: IDENTIFY password
                  NickServ Syntax: IDENTIFY password
>> :NickServ!service@rizon.net NOTICE hentai_god :/msg NickServ HELP IDENTIFY for more information.
                  NickServ /msg NickServ HELP IDENTIFY for more information.
<< privmsg NickServ :IDENTIFY password
privmsg NickServ :IDENTIFY password
>> :NickServ!service@rizon.net NOTICE hentai_god :Password incorrect.
                  NickServ Password incorrect.

I have wrote a alias for /msg, though I don't know if it is the best way to go about it
`--- kirc.c.bak  2023-01-05 15:15:42.491099907 +0200
+++ kirc.c      2023-01-05 20:17:12.858459546 +0200
@@ -953,7 +953,16 @@
        }
        printf("\r\x1b[0K");
        switch (l->buf[0]) {
-       case '/' : /* send system command */
+       case '/' :{
+                /* send system command */
+               if(!strncmp(l->buf+1, "MSG", 3)||!strncmp(l->buf+1, "msg", 3)){
+                       strtok_r(l->buf + 5, " ", &tok);
+                       if(*(tok+strlen(tok)+1))
+                               *(tok+strlen(tok))=' ';
+                       raw("privmsg %s :%s\r\n", l->buf + 5, tok);
+                        printf("\x1b[35mprivmsg %s :%s\x1b[0m\r\n", l->buf + 5, tok);
+               }
+               else
                if (l->buf[1] == '#') {
                        strcpy(cdef, l->buf + 2);
                        printf("\x1b[35mnew channel: #%s\x1b[0m\r\n", cdef);
@@ -961,6 +970,7 @@
                        raw("%s\r\n", l->buf + 1);
                        printf("\x1b[35m%s\x1b[0m\r\n", l->buf);
                }
+               }
                break;
        case '@' : /* send private message to target channel or user */
                strtok_r(l->buf, " ", &tok);
`
using /msg with this I get

<< privmsg NickServ :IDENTIFY password
privmsg NickServ :IDENTIFY password
>> :NickServ!service@rizon.net NOTICE hentai_god :Password incorrect.
                  NickServ Password incorrect.

**Comment by stefan11111** [comment] 2023-01-07 00:39
I would like to point out another issue that is both is this repo and in ekekoi's repo.
if I start kirc without the -c option, when I join a channel the prompt stays empty and I can't send messages normally(by typing normally and pressing enter), instead I have to use privmsg and specify the channel manually.

<< privmsg # :test message
privmsg # :test message
>> :irc.rizon.cc 404 hentai_god # :Cannot send to channel
              irc.rizon.cc # Cannot send to channel

The issue might be related to the fact that static void raw_parser(char *string) function fills param_t p with incorrect data.

**Comment by stefan11111** [comment] 2023-01-10 14:27
@mcpcpc @emekoi 
I have pinged you because I think this is an important bug.

I have found a fix for this issue:

```
if(!strncmp(l->buf + 1, "JOIN", 4)||!strncmp(l->buf + 1, "join", 4)){
		if(!strchr(l->buf, '#')){
			printf("\x1b[35m%s\x1b[0m\r\n", l->buf);
			printf("\x1b[35mIllegal channel!\x1b[0m\r\n");
		} else {
	                chan = strchr(l->buf, '#');
			chan ++;
			strcpy(l->prompt, chan);
			raw("join #%s\r\n", chan);
			printf("\x1b[35m%s\x1b[0m\r\n", l->buf);
			printf("\x1b[35mJoined #%s!\x1b[0m\r\n", chan);
		}
	} else
	if(!strncmp(l->buf + 1, "PART", 4)||!strncmp(l->buf + 1, "part", 4)){
		tok = strchr(l->buf, '#');
		if(strlen(l->buf) == 5){
        	    raw("part #%s\r\n", chan);
		    printf("\x1b[35m%s\x1b[0m\r\n", l->buf);
        	    printf("\x1b[35mLeft #%s!\r\n", chan);
            	    printf("\x1b[35mYou need to use /join or /# to speak in a channel!\x1b[0m\r\n");
            	    chan = NULL;
            	    strcpy(l->prompt, "");
		} else
		if(tok){
            	    raw("part %s\r\n", tok);
            	    printf("\x1b[35m%s\x1b[0m\r\n", l->buf);
            	    printf("\x1b[35mLeft %s!\r\n", tok);
            	    printf("\x1b[35mYou need to use /join or /# to speak in a channel!\x1b[0m\r\n");
            	    chan = NULL;
            	    strcpy(l->prompt, "");
		} else {
		    int ok = 1;
		    tok = l->buf + 5;
		    while(*tok){
			if(*tok!=' '){
			    ok = 0;
			    break;
			}
			tok ++;
		    }
		    if(ok){
			chan = l->prompt;
                	printf("\n\n\n%s\n\n\n", chan);
                	raw("part #%s\r\n", chan);
                	printf("\x1b[35m%s\x1b[0m\r\n", l->buf);
                	printf("\x1b[35mLeft #%s!\r\n", chan);
                	printf("\x1b[35mYou need to use /join or /# to speak in a channel!\x1b[0m\r\n");
                	chan = NULL;
                	strcpy(l->prompt, "");
		    } else {
			printf("\x1b[35m%s\x1b[0m\r\n", l->buf);
			printf("\x1b[35mIllegal channel!\x1b[0m\r\n");
		    }
		}
	} else
```

Adding this snippet of code to the handle_user_,input() function solves the problem and adds useful messages.

**Comment by stefan11111** [comment] 2023-01-19 21:17
I have decided to make a pull request as I have added a lot of features, including @emekoi's dcc patch.
The features include all that I have wrote above and a bit more

**Comment by mcpcpc** [comment] 2023-01-20 02:05
> I have decided to make a pull request as I have added a lot of features, including @emekoi's dcc patch.
> The features include all that I have wrote above and a bit more

Thanks! PR looks good so far.  I will plan on merging in the in next day or two after some more user testing.

**Comment by emekoi** [comment] 2023-01-20 03:55
@stefan11111 
> I would like to point out another issue that is both is this repo and in ekekoi's repo. if I start kirc without the -c option, when I join a channel the prompt stays empty and I can't send messages normally(by typing normally and pressing enter), instead I have to use privmsg and specify the channel manually.

kinda late, but that's because when you use `-c <channel>` it automatically sets `cdef` to `<channel>`, so messages typed in without a prefix (`@` or `/`) are automatically translated to `PRIVMSG #<cdef> :<your message>`. if you start without `-c` and manually join a channel you need to type `/#<channel>` to manually set `cdef` and then the behavior is as if you had started with `-c <channel>`.

also is the special-casing for `/msg` needed? i'm pretty sure in your initial attempt you were just missing the `:` in the command. testing with a local irc server using ergochat i get similar response in both cases
```
<< privmsg NickServ IDENTIFY password
/privmsg NickServ IDENTIFY password
>> :NickServ!NickServ@localhost NOTICE foobar :Invalid parameters. For usage, do /msg NickServ HELP IDENTIFY
                  NickServ Invalid parameters. For usage, do /msg NickServ HELP IDENTIFY 
<< privmsg NickServ :IDENTIFY password
/privmsg NickServ :IDENTIFY password
>> :NickServ!NickServ@localhost NOTICE foobar :Authentication failed: Account does not exist
                  NickServ Authentication failed: Account does not exist 
```
similarly i don't think the special-casing for `part` or `join` is needed either. also i think your editor is  set to tabs while the rest of the file uses spaces.

**Comment by stefan11111** [comment] 2023-01-20 07:50
The dcc patch you wrote has been working without issue for me. Thanks for writing it as it helped me get rid of hexchat for good.

I wrote special-casting for /msg because most of the time I paste the command directly from some sites
(usually nibl and subsplease). It is very annoying to have to edit the commands all the time instead of just copy-pasting. The /msg command is used very often. So often in fact that I have only heard of the /privmsg command in this issue. 

I wrote special-casting for /join because you should be able to send messages normally after using /join, and you shouldn't have to /use /privmsg or @ or /# to do that. It should work just like the -c option. I also added some messages to notify the user of changing the channel.

I wrote special-casting for /part because I wanted to empty the prompt and make the user unable to speak in the channel normally without first using /join or /#. I also added a message for this.

Regarding the indentation, I agree it could be better. It happened because I wrote on the same file in three different editors. I know it's not good and that the indentation may need to be changed.

One thing regarding dcc though. Setting the CON_MAX variable to 4 is way too low. It should be at least 6 (downloading 6 files from two bots, three from each). It is often that I have more than 4 downloads at the same time. I have set it to 10 as to not hit it in most use cases.

Regarding the issue of config files, as mentioned your patch's comments, we could use a header file like the suckless guys or make a separate config file to put in the user's directory (a dot file). I would prefer the first approach as in is the most minimal.

**Comment by stefan11111** [comment] 2023-01-20 21:19
@mcpcpc  @emekoi 

I have looked into the reasons why codacity screams about my pr. It has issues with 4 lines of code. I will use line numbers as reported by codacity.

line 1018: if(strlen(l->buf) == 5){

There should be no issues with this line as l->buf will always be null terminated.

line 1066: if(*(tok+strlen(tok)+1))
line 1067: *(tok+strlen(tok))=' ';

These lines only introduce bugs and I should have never added them. I will make a commit that removes them.

line 1267: int n = read(dcc_sessions.sock_fds[i].fd, buf, BUFSIZ);

I have no idea what codacity finds wrong about this. Keep in mind that this part of @emekoi' s commit, so I may not be too knowledgeable about it.

Regarding line 1069, the one the code review is about.
It makes sure that the password that is sent to NickServ is not printed on the screen, as it can be an annoyance and a security concern.
However, It appears that if the user sends a message no NickServ with more than one space between /msg and NickServ the password is still printed to the screen. I will also address this in the next commit.

**Comment by mcpcpc** [comment] 2023-01-20 23:39
> While testing, I found that if you use tabs in your message, the message prompt goes haywire (not to be confused with the prompt that shows the current channel). This issue was not added in my pr or emekoi's , as it still happens in the this repo without any modifications.

confirmed. Please open a separate issue for this one. I think one of the previous releases may have broken tabs in the buffer

**Comment by mcpcpc** [comment] 2023-03-19 02:05
merged as a separate feature for the time being (see #135)

**Closed by mcpcpc** 2023-03-19 02:05 UTC
Labels: enhancement
